version: "3"

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task -l

  start-localstack:
    desc: Start LocalStack using Docker Compose
    cmds:
      - docker-compose -f compose.yml up

  stop-localstack:
    desc: Stop LocalStack using Docker Compose
    cmds:
      - docker-compose -f compose.yml down

  stree-local:
    cmds:
      - go run main.go my-bucket/test/dir2 --local
    desc: Run the stree application with specified arguments

  stree-help:
    cmds:
      - go run main.go --help
    desc: Display help for the stree application

  ls-local:
    desc: List all objects in S3 bucket
    cmds:
      - aws s3 ls s3://my-bucket/ --recursive --profile local --region us-east-1 --endpoint-url=http://localhost:4566
